version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: universalapi-redis
    networks:
      - internal-net

  universalapi:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    container_name: universalapi
    depends_on:
      - redis
    ports:
      - "127.0.0.1:9504:9504" # Spring Boot on port 9504 (localhost only)
    networks:
      - internal-net
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=9504 # Override default Spring Boot port

networks:
  internal-net:
    driver: bridge
