version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: universalapi-redis
    ports:
      - "6379:6379"  # Publish Redis port to the host

  universalapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: universalapi
    depends_on:
      - redis
    network_mode: host  # Use host networking so localhost is shared with the host
    environment:
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379
      - SERVER_PORT=9504
